# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - master
      - v*-devel
  pull_request:
    branches:
      - master
      - v*-devel

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with two commits
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install -y -q tox

      - name: Lint with flake8
        run: |
          tox -eflake8

  build38:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with two commits
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install -y -q tox

      - name: Test with python 3.8
        run: |
          tox -epy3

      - name: Test with python 3.8 again
        run: |
          tox -epy3

      - name: Test with python 3.8 again again
        run: |
          tox -epy3
